### ISSUE TITLE
Terraform apply finished with error: Provider produced inconsistent final plan

### ISSUE THREAD

**Issue by Draqun** [heroku/terraform-provider-heroku#320]
Hi.
I want deploy my app on heroku using terraform but when I run apply there is an error with message `Provider produced inconsistent final plan`. Can anyone check what is wrong with my configuration. Code can be found here: https://gitlab.com/Draqun/pa-forum 

### Terraform Version
Terraform comes from `hashicorp/terraform:1.0.6` and has a version Terraform v1.0.6

### Heroku Provider Version
Run `terraform -v` to show core and any provider versions. A sample output could be:

```
Terraform v0.11.7
+ provider.heroku v1.1.0
```

### Terraform Configuration Files
https://gitlab.com/Draqun/pa-forum/-/blob/master/terraform/main.tf

### Debug Output
https://gitlab.com/Draqun/pa-forum/-/jobs/1586468441

### Expected Behavior
Terraform scripts comes from https://learn.hashicorp.com/tutorials/terraform/heroku-provider?in=terraform/applications and I thought it works.

### Actual Behavior
`Provider produced inconsistent final plan`

### Steps to Reproduce
https://gitlab.com/Draqun/pa-forum/-/blob/master/.gitlab-ci.yml#L67

**Comment by mars** [comment]
> Terraform v0.11.7
>   \+ provider.heroku v1.1.0

The description reflects a very old version of both Terraform & this provider. We cannot support such a configuration.

Please upgrade to Terraform 1.0 and terraform-provider-heroku 4.6.0.

**Comment by Draqun** [comment]
Hi.

I think I have not been understood. Problem occurs into CICD when I use hashicorp/terraform:1.0.6 docker image and provider version declared into terraform script is version = "~> 4.6.0", which means I have the latest version.

**Comment by mars** [comment]
The relevant lines from your debug output:

```
When expanding the plan for heroku_build.pa_forum_build to include new
values learned so far during apply, provider
"registry.terraform.io/heroku/heroku" produced an invalid new value for
.local_checksum: was
cty.StringVal("SHA256:c6867fe33fb07348e97c62c99725ba05d1239e87e17c6e521ec6a02be17740fa"),
but now
cty.StringVal("SHA256:f4b47b9a5a95eeedb986455e5c9dab0c926ed8bc8851bf39777f483a337b33ab").
```

So, looking at your `main.tf` configuration file, I see:

```hcl
resource "heroku_build" "pa_forum_build" {
  app = heroku_app.pa_forum.id

  source {
    path = "../"
  }
}
```

This exact path issue is described in the provider docs, [using `heroku_build` with local source directory](https://registry.terraform.io/providers/heroku/heroku/latest/docs/resources/build#local-source):

> * avoid ancestor paths that contain the Terraform configuration itself
> * paths such as `../` will cause errors during apply

Your source directory `../` includes the `terraform/` configuration directory itself, which Terraform writes files to during the plan/apply process. Therefore, it will end up having a different checksum after Terraform calculates the plan.

To solve, rearrange the repo so that the Terraform configuration is not included in the `source.path`. We typically put Terraform configuration at the top-level of the repo, with all sources in a `src/` sub-directory, like those docs describe.

**Comment by Draqun** [comment]
And all is clear. Thank you for you time.
