### ISSUE TITLE
How to Specify `entrypoint` for `heroku_app` ?

### ISSUE THREAD

**Issue by matifali** [heroku/terraform-provider-heroku#371]
### Heroku Provider Version
Run `terraform -v` to show core and any provider versions. A sample output could be:

```
Terraform v1.4.5
+ provider registry.terraform.io/coder/coder v0.7.0
+ provider registry.terraform.io/heroku/heroku v5.2.1
```

### Affected Resource(s)
Please list the resources as a list, for example:
- heroku_app
- heroku_build

### Terraform Configuration Files
```hcl-terraform

variable "heroku_api_key" {
  type        = string
  sensitive   = true
}

provider "heroku" {
  api_key = var.heroku_api_key
}

resource "heroku_app" "workspace" {
  name   = "heroku-workspace"
  region = data.coder_parameter.region.value
  stack  = "container"
}

resource "heroku_build" "workspace" {
  app_id = heroku_app.workspace.id
  source {
    path = "build/Dockerfile"
  }
}

resource "heroku_formation" "workspace" {
  app_id     = heroku_app.workspace.id
  type       = "web"
  size       = "standard-1x"
  quantity   = 1
  depends_on = [heroku_build.workspace]
}
```

### Request

How can I specify a custom `entrypoint` from the terraform file?

**Comment by mars** [comment]
See [Building Docker Images with heroku.yml, Defining the processes to run](https://devcenter.heroku.com/articles/build-docker-images-heroku-yml#run-defining-the-processes-to-run),
> If you do not include a `run` section in your `heroku.yml` manifest, the `Dockerfile` `CMD` is used instead.

**Comment by matifali** [comment]
But how would I pass a script from the terraform to the Dockerfile?

**Comment by matifali** [comment]
Would you consider re-opening this, as your suggested solution does not work for my use case?
Thanks, @mars

**Comment by mars** [comment]
There's no point re-opening this issue here on the Terraform provider, because Heroku does not support how you're attempting to use it (passing unbound script data as an argument to start the process). Heroku expects the app's source code to by built into the container, not dynamically loaded from start-up parameters.

Looking at the code you linked above, that Docker image will have some other incompabilities with Heroku, such as the port assignments. It's not clear how any of this intersects with this Terraform Provider for Heroku, because `heroku` does not appear as a provider or resource anywhere in that TF configuration.
